# Generated by Django 4.2.9 on 2024-02-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_value', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
