# Generated by Django 4.2.9 on 2024-04-22 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_name_item_name_item_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
