# Generated by Django 4.2.9 on 2024-06-28 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_city_delete_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='volume',
            field=models.IntegerField(null=True),
        ),
    ]
