# Generated by Django 4.2.9 on 2024-09-19 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_financials'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
