# Generated by Django 4.2.9 on 2024-09-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_bids_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=25, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('turnover', models.IntegerField(blank=True, null=True)),
                ('total_assets', models.IntegerField(blank=True, null=True)),
                ('total_liabilities', models.IntegerField(blank=True, null=True)),
                ('operating_profit', models.IntegerField(blank=True, null=True)),
                ('net_income', models.IntegerField(blank=True, null=True)),
                ('free_cash_flow', models.IntegerField(blank=True, null=True)),
                ('shareholder_funds', models.IntegerField(blank=True, null=True)),
                ('interest_expense', models.IntegerField(blank=True, null=True)),
                ('long_term_debt', models.IntegerField(blank=True, null=True)),
                ('equity', models.IntegerField(blank=True, null=True)),
                ('operating_margin', models.FloatField(blank=True, null=True)),
                ('net_profit_margin', models.FloatField(blank=True, null=True)),
                ('free_cash_flow_margin', models.FloatField(blank=True, null=True)),
                ('interest_cover', models.FloatField(blank=True, null=True)),
                ('return_on_assets', models.FloatField(blank=True, null=True)),
                ('gearing', models.FloatField(blank=True, null=True)),
                ('solvency_ratio', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
